---
title: GV IoT Platform
timezone: UTC

theme: jekyll-theme-cayman
images: /assets/images
logo: /assets/images/gviot-logo.png
permalink: pretty
owner_url:
  url: http://www.greenvulcano.com/
defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "default_page"
