---
title: GV IoT Platform
timezone: UTC

theme: jekyll-theme-cayman
images: /pages
logo: /pages/images/logo_gviot.png
permalink: pretty
owner_url:
  url: http://www.greenvulcano.com/
defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "default_page"
