---
title: GV IoT Platform
description: GV IoT Platform Documentation
timezone: UTC

theme: minimal-mistakes-jekyll
images: /pages
logo: /pages/images/logo_gviot.png
permalink: pretty
owner_url:
  url: http://www.greenvulcano.com/
defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "default"
      author: "Me"
